# Generated by Django 3.2.4 on 2021-06-09 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patient',
            fields=[
                ('p_username', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('p_fname', models.CharField(max_length=50)),
                ('p_lname', models.CharField(max_length=50)),
                ('p_email', models.EmailField(max_length=100, unique=True)),
                ('p_password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='reseptionist',
            fields=[
                ('r_username', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('r_password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=50)),
                ('service_price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
