# Generated by Django 3.2.4 on 2021-06-28 22:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField(null=True)),
                ('appointment_time', models.TimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Physician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph_id', models.CharField(max_length=15, unique=True)),
                ('ph_first_name', models.CharField(max_length=50)),
                ('ph_last_name', models.CharField(max_length=50)),
                ('ph_speciality', models.IntegerField(choices=[(0, 'General Dentist'), (1, 'Periodontist'), (2, 'Oral and Maxillofacial Surgeon'), (3, 'Nurse')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Reseptionist',
            fields=[
                ('r_username', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('r_password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=50)),
                ('service_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('physician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brightside.physician')),
            ],
        ),
        migrations.CreateModel(
            name='Ph_service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brightside.physician')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brightside.service')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_first_name', models.CharField(max_length=50)),
                ('p_last_name', models.CharField(max_length=50)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_id', models.CharField(max_length=15, unique=True)),
                ('bill_date', models.DateTimeField(null=True)),
                ('bill_status', models.IntegerField(choices=[(0, 'Paid'), (1, 'Unpaid')], default=1)),
                ('total_pay', models.DecimalField(decimal_places=2, max_digits=8)),
                ('payment_method', models.IntegerField(choices=[(0, 'VISA'), (1, 'Master Card'), (2, 'Cash'), (3, 'Knet')], default=0)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='brightside.appointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brightside.patient')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brightside.patient'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='physician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brightside.physician'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reseptionist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='brightside.reseptionist'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brightside.service'),
        ),
    ]
