# Generated by Django 3.2.4 on 2021-06-19 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_id', models.CharField(max_length=15, unique=True)),
                ('bill_date', models.DateTimeField(null=True)),
                ('bill_status', models.IntegerField(choices=[(0, 'Paid'), (1, 'Unpaid')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('p_username', models.CharField(max_length=50, unique=True)),
                ('p_first_name', models.CharField(max_length=50)),
                ('p_last_name', models.CharField(max_length=50)),
                ('p_email', models.EmailField(max_length=100, unique=True)),
                ('p_password', models.CharField(max_length=100)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Physician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph_id', models.CharField(max_length=15, unique=True)),
                ('ph_first_name', models.CharField(max_length=50)),
                ('ph_last_name', models.CharField(max_length=50)),
                ('ph_speciality', models.IntegerField(choices=[(0, 'General Dentist'), (1, 'Periodontist'), (2, 'Oral and Maxillofacial Surgeon'), (3, 'Nurse')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Reseptionist',
            fields=[
                ('r_username', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('r_password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=50)),
                ('service_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('physician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brightside.physician')),
            ],
        ),
        migrations.CreateModel(
            name='Ph_service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brightside.physician')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brightside.service')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_id', models.CharField(max_length=15, unique=True)),
                ('total_pay', models.CharField(max_length=15)),
                ('payment_date', models.DateTimeField(null=True)),
                ('status', models.IntegerField(choices=[(0, 'Paid'), (1, 'Unpaid')], default=1)),
                ('payment_method', models.IntegerField(choices=[(0, 'VISA'), (1, 'Master Card'), (2, 'Cash'), (3, 'Knet')], default=0)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brightside.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField(null=True)),
                ('appointment_time', models.TimeField(null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brightside.patient')),
                ('physician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brightside.physician')),
                ('reseptionist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='brightside.reseptionist')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brightside.service')),
            ],
        ),
    ]
