# Generated by Django 3.2.4 on 2021-06-15 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brightside', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physician',
            name='ph_speciality',
            field=models.IntegerField(choices=[(0, 'General Dentist'), (1, 'Periodontist'), (2, 'Oral and Maxillofacial Surgeon')], default=0),
        ),
    ]
