# Generated by Django 3.2.4 on 2021-06-16 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brightside', '0002_alter_physician_ph_speciality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='reseptionist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='brightside.reseptionist'),
        ),
    ]
