# Generated by Django 3.2.4 on 2021-06-16 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brightside', '0003_alter_appointment_reseptionist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.IntegerField(choices=[(0, 'VISA'), (1, 'Master Card'), (2, 'Cash'), (3, 'Knet')], default=0),
        ),
    ]
