# Generated by Django 3.2.4 on 2021-06-18 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brightside', '0004_alter_payment_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='appointment_id',
        ),
    ]
